name: Build Master JSON

on:
  push:
    paths:
      - "by_divison/**/*.json"
      - "by_infrastructure_component/networks/*.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Combine JSON files
        run: |
          python by_division/generated/generate_master_list.py
          python by_infrastructe_component/networks/generate_master_list.py

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add by_divison/generated/networks.json by_infrastructure_component/networks/master-generated.json
          git commit -m "Update master.json"
          git push
